[build]
  command = "CI= npm run build"
  publish="/build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	no-cache, 
	no-store'''
[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    charset = "UTF-8"
