[build]
  command = "CI= npm run build"
  publish="lomalaskuri/build"
  base = "/lomalaskuri"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	no-cache, 
	no-store'''
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    charset = "UTF-8"
