[build]
  command = "CI= npm run build"
  publish="lomalaskuri/build"
  base = "/lomalaskuri"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	must-revalidate'''
